//
// Generated by Bluespec Compiler, version 2022.01-5-ge3edf4b1 (build e3edf4b1)
//
// On Fri Apr 15 12:45:56 EDT 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_inst_response_put          O     1 reg
// rx_from_stage0_deq_ena         O     1
// tx_to_stage2_enq_ena           O     1
// tx_to_stage2_enq_data          O   119
// tx_to_stage2_inst_enq_ena      O     1
// tx_to_stage2_inst_enq_data     O    32
// RDY_update_eEpoch              O     1 const
// RDY_update_wEpoch              O     1 const
// RDY_csr_misa_c                 O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// inst_response_put              I    41
// rx_from_stage0_notEmpty_b      I     1
// rx_from_stage0_first_deq_rdy_b  I     1
// rx_from_stage0_first_x         I    77
// tx_to_stage2_notFull_b         I     1
// tx_to_stage2_enq_rdy_b         I     1
// tx_to_stage2_inst_notFull_b    I     1 unused
// tx_to_stage2_inst_enq_rdy_b    I     1
// csr_misa_c_c                   I     1
// EN_inst_response_put           I     1
// EN_update_eEpoch               I     1
// EN_update_wEpoch               I     1
// EN_csr_misa_c                  I     1
//
// Combinational paths from inputs to outputs:
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    tx_to_stage2_notFull_b,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> rx_from_stage0_deq_ena
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_notFull_b,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_enq_ena
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_notFull_b,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_enq_data
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_notFull_b,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_inst_enq_ena
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_notFull_b,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_inst_enq_data
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkstage1(CLK,
		RST_N,

		inst_response_put,
		EN_inst_response_put,
		RDY_inst_response_put,

		rx_from_stage0_notEmpty_b,

		rx_from_stage0_first_deq_rdy_b,

		rx_from_stage0_first_x,

		rx_from_stage0_deq_ena,

		tx_to_stage2_notFull_b,

		tx_to_stage2_enq_rdy_b,

		tx_to_stage2_enq_ena,

		tx_to_stage2_enq_data,

		tx_to_stage2_inst_notFull_b,

		tx_to_stage2_inst_enq_rdy_b,

		tx_to_stage2_inst_enq_ena,

		tx_to_stage2_inst_enq_data,

		EN_update_eEpoch,
		RDY_update_eEpoch,

		EN_update_wEpoch,
		RDY_update_wEpoch,

		csr_misa_c_c,
		EN_csr_misa_c,
		RDY_csr_misa_c);
  parameter [63 : 0] hartid = 64'b0;
  input  CLK;
  input  RST_N;

  // action method inst_response_put
  input  [40 : 0] inst_response_put;
  input  EN_inst_response_put;
  output RDY_inst_response_put;

  // action method rx_from_stage0_notEmpty
  input  rx_from_stage0_notEmpty_b;

  // action method rx_from_stage0_first_deq_rdy
  input  rx_from_stage0_first_deq_rdy_b;

  // action method rx_from_stage0_first
  input  [76 : 0] rx_from_stage0_first_x;

  // value method rx_from_stage0_deq_ena
  output rx_from_stage0_deq_ena;

  // action method tx_to_stage2_notFull
  input  tx_to_stage2_notFull_b;

  // action method tx_to_stage2_enq_rdy
  input  tx_to_stage2_enq_rdy_b;

  // value method tx_to_stage2_enq_ena
  output tx_to_stage2_enq_ena;

  // value method tx_to_stage2_enq_data
  output [118 : 0] tx_to_stage2_enq_data;

  // action method tx_to_stage2_inst_notFull
  input  tx_to_stage2_inst_notFull_b;

  // action method tx_to_stage2_inst_enq_rdy
  input  tx_to_stage2_inst_enq_rdy_b;

  // value method tx_to_stage2_inst_enq_ena
  output tx_to_stage2_inst_enq_ena;

  // value method tx_to_stage2_inst_enq_data
  output [31 : 0] tx_to_stage2_inst_enq_data;

  // action method update_eEpoch
  input  EN_update_eEpoch;
  output RDY_update_eEpoch;

  // action method update_wEpoch
  input  EN_update_wEpoch;
  output RDY_update_wEpoch;

  // action method csr_misa_c
  input  csr_misa_c_c;
  input  EN_csr_misa_c;
  output RDY_csr_misa_c;

  // signals for module outputs
  wire [118 : 0] tx_to_stage2_enq_data;
  wire [31 : 0] tx_to_stage2_inst_enq_data;
  wire RDY_csr_misa_c,
       RDY_inst_response_put,
       RDY_update_eEpoch,
       RDY_update_wEpoch,
       rx_from_stage0_deq_ena,
       tx_to_stage2_enq_ena,
       tx_to_stage2_inst_enq_ena;

  // inlined wires
  wire ff_memory_response_dequeueing_whas, tx_tostage2_w_ena_whas;

  // register rg_action
  reg rg_action;
  wire rg_action_D_IN, rg_action_EN;

  // register rg_eEpoch
  reg rg_eEpoch;
  wire rg_eEpoch_D_IN, rg_eEpoch_EN;

  // register rg_prev
  reg [93 : 0] rg_prev;
  wire [93 : 0] rg_prev_D_IN;
  wire rg_prev_EN;

  // register rg_receiving_upper
  reg rg_receiving_upper;
  wire rg_receiving_upper_D_IN, rg_receiving_upper_EN;

  // register rg_wEpoch
  reg rg_wEpoch;
  wire rg_wEpoch_D_IN, rg_wEpoch_EN;

  // ports of submodule ff_memory_response_beforeDeq
  wire ff_memory_response_beforeDeq_D_IN,
       ff_memory_response_beforeDeq_EN,
       ff_memory_response_beforeDeq_Q_OUT;

  // ports of submodule ff_memory_response_beforeEnq
  wire ff_memory_response_beforeEnq_D_IN, ff_memory_response_beforeEnq_EN;

  // ports of submodule ff_memory_response_ff
  wire [40 : 0] ff_memory_response_ff_D_IN, ff_memory_response_ff_D_OUT;
  wire ff_memory_response_ff_CLR,
       ff_memory_response_ff_DEQ,
       ff_memory_response_ff_EMPTY_N,
       ff_memory_response_ff_ENQ,
       ff_memory_response_ff_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_ff_memory_response_dequeue,
       CAN_FIRE_RL_ff_memory_response_enqueue,
       CAN_FIRE_RL_process_instruction,
       CAN_FIRE_csr_misa_c,
       CAN_FIRE_inst_response_put,
       CAN_FIRE_rx_from_stage0_first,
       CAN_FIRE_rx_from_stage0_first_deq_rdy,
       CAN_FIRE_rx_from_stage0_notEmpty,
       CAN_FIRE_tx_to_stage2_enq_rdy,
       CAN_FIRE_tx_to_stage2_inst_enq_rdy,
       CAN_FIRE_tx_to_stage2_inst_notFull,
       CAN_FIRE_tx_to_stage2_notFull,
       CAN_FIRE_update_eEpoch,
       CAN_FIRE_update_wEpoch,
       WILL_FIRE_RL_ff_memory_response_dequeue,
       WILL_FIRE_RL_ff_memory_response_enqueue,
       WILL_FIRE_RL_process_instruction,
       WILL_FIRE_csr_misa_c,
       WILL_FIRE_inst_response_put,
       WILL_FIRE_rx_from_stage0_first,
       WILL_FIRE_rx_from_stage0_first_deq_rdy,
       WILL_FIRE_rx_from_stage0_notEmpty,
       WILL_FIRE_tx_to_stage2_enq_rdy,
       WILL_FIRE_tx_to_stage2_inst_enq_rdy,
       WILL_FIRE_tx_to_stage2_inst_notFull,
       WILL_FIRE_tx_to_stage2_notFull,
       WILL_FIRE_update_eEpoch,
       WILL_FIRE_update_wEpoch;

  // declarations used by system tasks
  // synopsys translate_off
  reg TASK_testplusargs___d310;
  reg TASK_testplusargs___d311;
  reg TASK_testplusargs___d312;
  reg [63 : 0] v__h5109;
  reg TASK_testplusargs___d24;
  reg TASK_testplusargs___d25;
  reg TASK_testplusargs___d26;
  reg [63 : 0] v__h1778;
  reg TASK_testplusargs___d125;
  reg TASK_testplusargs___d126;
  reg TASK_testplusargs___d127;
  reg [63 : 0] v__h2403;
  reg TASK_testplusargs___d161;
  reg TASK_testplusargs___d162;
  reg TASK_testplusargs___d163;
  reg [63 : 0] v__h4084;
  reg TASK_testplusargs___d192;
  reg TASK_testplusargs___d193;
  reg TASK_testplusargs___d194;
  reg [63 : 0] v__h4378;
  reg TASK_testplusargs___d252;
  reg TASK_testplusargs___d253;
  reg TASK_testplusargs___d254;
  reg [63 : 0] v__h4867;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d261;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d265;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d271;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d273;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d278;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d280;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d292;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d300;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d303;
  reg TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d306;
  reg TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d37;
  reg TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d40;
  reg TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d46;
  reg TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d48;
  reg TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d52;
  reg TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d54;
  reg NOT_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff__ETC___d130;
  reg TASK_testplusargs_61_OR_TASK_testplusargs_62_A_ETC___d183;
  reg TASK_testplusargs_61_OR_TASK_testplusargs_62_A_ETC___d187;
  reg TASK_testplusargs_92_OR_TASK_testplusargs_93_A_ETC___d198;
  reg TASK_testplusargs_92_OR_TASK_testplusargs_93_A_ETC___d199;
  reg rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257;
  reg TASK_testplusargs_10_OR_TASK_testplusargs_11_A_ETC___d318;
  reg TASK_testplusargs_10_OR_TASK_testplusargs_11_A_ETC___d320;
  // synopsys translate_on

  // remaining internal signals
  wire [63 : 0] IF_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_m_ETC___d176,
		rx_from_stage0_first_x_BITS_76_TO_13__q1,
		x1_avValue_fst_address__h4147,
		x1_avValue_fst_address__h4153,
		x1_avValue_snd_fst_address__h4156,
		x1_avValue_snd_fst_address__h4159,
		x1_avValue_snd_snd_snd_pc__h3865,
		x1_avValue_snd_snd_snd_pc__h3869,
		x1_avValue_snd_snd_snd_snd_pc__h3764,
		x1_avValue_snd_snd_snd_snd_snd_pc__h3831,
		x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3873,
		x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3877,
		x_pc__h3679,
		y_avValue_fst_address__h4150;
  wire [31 : 0] IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73,
		final_instruction___1__h4662,
		final_instruction__h3646,
		pipedata_instruction__h4651,
		y_avValue_snd_fst__h3841,
		y_avValue_snd_snd_snd_fst__h3718,
		y_avValue_snd_snd_snd_fst__h3720,
		y_avValue_snd_snd_snd_fst__h3779,
		y_avValue_snd_snd_snd_fst__h3781;
  wire [15 : 0] x1_avValue_snd_snd_snd_instruction__h3866,
		x1_avValue_snd_snd_snd_instruction__h3870,
		x1_avValue_snd_snd_snd_snd_instruction__h3765,
		x1_avValue_snd_snd_snd_snd_snd_instruction__h3832,
		x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3874,
		x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3878,
		x_instruction__h3680;
  wire [13 : 0] rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_CONCAT_IF_rg__ETC___d159;
  wire [12 : 0] IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d248;
  wire [11 : 0] IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d155,
		IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d156,
		IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d157;
  wire [9 : 0] IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d246;
  wire [7 : 0] x1_avValue_fst_history__h4736;
  wire [5 : 0] cause__h4016;
  wire [1 : 0] curr_epoch__h1681,
	       x1_avValue_fst_prediction__h4721,
	       x1_avValue_fst_prediction__h4725,
	       x1_avValue_fst_prediction__h4729,
	       x1_avValue_fst_prediction__h4733,
	       x__h2690,
	       y__h2086,
	       y_avValue_fst_prediction__h4704,
	       y_avValue_fst_prediction__h4717;
  wire IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d243,
       IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d289,
       IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d120,
       IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d218,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d103,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d219,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d227,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d260,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d264,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d277,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d291,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d299,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d302,
       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d305,
       IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d182,
       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d186,
       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d225,
       IF_rg_prev_9_BIT_8_4_THEN_rg_prev_9_BITS_11_TO_ETC___d97,
       IF_rx_fromstage0_w_data_whas__0_THEN_rx_fromst_ETC___d100,
       NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d113,
       NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205,
       NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d91,
       NOT_rg_receiving_upper_01_67_OR_IF_ff_memory_r_ETC___d270,
       ff_memory_response_beforeDeq_read_AND_ff_memor_ETC___d19,
       rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89,
       rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64;

  // action method inst_response_put
  assign RDY_inst_response_put = ff_memory_response_ff_FULL_N ;
  assign CAN_FIRE_inst_response_put = ff_memory_response_ff_FULL_N ;
  assign WILL_FIRE_inst_response_put = EN_inst_response_put ;

  // action method rx_from_stage0_notEmpty
  assign CAN_FIRE_rx_from_stage0_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_from_stage0_notEmpty = 1'd1 ;

  // action method rx_from_stage0_first_deq_rdy
  assign CAN_FIRE_rx_from_stage0_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_from_stage0_first_deq_rdy = 1'd1 ;

  // action method rx_from_stage0_first
  assign CAN_FIRE_rx_from_stage0_first = 1'd1 ;
  assign WILL_FIRE_rx_from_stage0_first = 1'd1 ;

  // value method rx_from_stage0_deq_ena
  assign rx_from_stage0_deq_ena = ff_memory_response_dequeueing_whas ;

  // action method tx_to_stage2_notFull
  assign CAN_FIRE_tx_to_stage2_notFull = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_notFull = 1'd1 ;

  // action method tx_to_stage2_enq_rdy
  assign CAN_FIRE_tx_to_stage2_enq_rdy = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_enq_rdy = 1'd1 ;

  // value method tx_to_stage2_enq_ena
  assign tx_to_stage2_enq_ena = tx_tostage2_w_ena_whas ;

  // value method tx_to_stage2_enq_data
  assign tx_to_stage2_enq_data =
	     { IF_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_m_ETC___d176,
	       pipedata_instruction__h4651,
	       curr_epoch__h1681,
	       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d227,
	       cause__h4016,
	       rg_receiving_upper &&
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d225,
	       IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d248 } ;

  // action method tx_to_stage2_inst_notFull
  assign CAN_FIRE_tx_to_stage2_inst_notFull = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_inst_notFull = 1'd1 ;

  // action method tx_to_stage2_inst_enq_rdy
  assign CAN_FIRE_tx_to_stage2_inst_enq_rdy = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_inst_enq_rdy = 1'd1 ;

  // value method tx_to_stage2_inst_enq_ena
  assign tx_to_stage2_inst_enq_ena = tx_tostage2_w_ena_whas ;

  // value method tx_to_stage2_inst_enq_data
  assign tx_to_stage2_inst_enq_data =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       y_avValue_snd_snd_snd_fst__h3718 :
	       y_avValue_snd_snd_snd_fst__h3720 ;

  // action method update_eEpoch
  assign RDY_update_eEpoch = 1'd1 ;
  assign CAN_FIRE_update_eEpoch = 1'd1 ;
  assign WILL_FIRE_update_eEpoch = EN_update_eEpoch ;

  // action method update_wEpoch
  assign RDY_update_wEpoch = 1'd1 ;
  assign CAN_FIRE_update_wEpoch = 1'd1 ;
  assign WILL_FIRE_update_wEpoch = EN_update_wEpoch ;

  // action method csr_misa_c
  assign RDY_csr_misa_c = 1'd1 ;
  assign CAN_FIRE_csr_misa_c = 1'd1 ;
  assign WILL_FIRE_csr_misa_c = EN_csr_misa_c ;

  // submodule ff_memory_response_beforeDeq
  RevertReg #(.width(32'd1),
	      .init(1'd1)) ff_memory_response_beforeDeq(.CLK(CLK),
							.D_IN(ff_memory_response_beforeDeq_D_IN),
							.EN(ff_memory_response_beforeDeq_EN),
							.Q_OUT(ff_memory_response_beforeDeq_Q_OUT));

  // submodule ff_memory_response_beforeEnq
  RevertReg #(.width(32'd1),
	      .init(1'd1)) ff_memory_response_beforeEnq(.CLK(CLK),
							.D_IN(ff_memory_response_beforeEnq_D_IN),
							.EN(ff_memory_response_beforeEnq_EN),
							.Q_OUT());

  // submodule ff_memory_response_ff
  FIFO2 #(.width(32'd41), .guarded(1'd0)) ff_memory_response_ff(.RST(RST_N),
								.CLK(CLK),
								.D_IN(ff_memory_response_ff_D_IN),
								.ENQ(ff_memory_response_ff_ENQ),
								.DEQ(ff_memory_response_ff_DEQ),
								.CLR(ff_memory_response_ff_CLR),
								.D_OUT(ff_memory_response_ff_D_OUT),
								.FULL_N(ff_memory_response_ff_FULL_N),
								.EMPTY_N(ff_memory_response_ff_EMPTY_N));

  // rule RL_process_instruction
  assign CAN_FIRE_RL_process_instruction =
	     ff_memory_response_beforeDeq_read_AND_ff_memor_ETC___d19 &&
	     rx_from_stage0_notEmpty_b &&
	     tx_to_stage2_notFull_b ;
  assign WILL_FIRE_RL_process_instruction = CAN_FIRE_RL_process_instruction ;

  // rule RL_ff_memory_response_enqueue
  assign CAN_FIRE_RL_ff_memory_response_enqueue =
	     EN_inst_response_put &&
	     (!ff_memory_response_dequeueing_whas ||
	      ff_memory_response_ff_EMPTY_N) ;
  assign WILL_FIRE_RL_ff_memory_response_enqueue =
	     CAN_FIRE_RL_ff_memory_response_enqueue ;

  // rule RL_ff_memory_response_dequeue
  assign CAN_FIRE_RL_ff_memory_response_dequeue =
	     ff_memory_response_dequeueing_whas &&
	     ff_memory_response_ff_EMPTY_N ;
  assign WILL_FIRE_RL_ff_memory_response_dequeue =
	     CAN_FIRE_RL_ff_memory_response_dequeue ;

  // inlined wires
  assign tx_tostage2_w_ena_whas =
	     WILL_FIRE_RL_process_instruction &&
	     rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	     NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 ;
  assign ff_memory_response_dequeueing_whas =
	     WILL_FIRE_RL_process_instruction &&
	     (rg_prev[15:14] == 2'b11 || rg_action ||
	      !rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64 ||
	      !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89) ;

  // register rg_action
  assign rg_action_D_IN =
	     !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 ||
	     !rg_action &&
	     rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64 ||
	     IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d120 ;
  assign rg_action_EN =
	     WILL_FIRE_RL_process_instruction &&
	     (NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d113 ||
	      !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89) ;

  // register rg_eEpoch
  assign rg_eEpoch_D_IN = ~rg_eEpoch ;
  assign rg_eEpoch_EN = EN_update_eEpoch ;

  // register rg_prev
  assign rg_prev_D_IN =
	     { x_pc__h3679,
	       x_instruction__h3680,
	       rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_CONCAT_IF_rg__ETC___d159 } ;
  assign rg_prev_EN = CAN_FIRE_RL_process_instruction ;

  // register rg_receiving_upper
  assign rg_receiving_upper_D_IN =
	     rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	     IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d103 ;
  assign rg_receiving_upper_EN =
	     WILL_FIRE_RL_process_instruction &&
	     NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d91 ;

  // register rg_wEpoch
  assign rg_wEpoch_D_IN = ~rg_wEpoch ;
  assign rg_wEpoch_EN = EN_update_wEpoch ;

  // submodule ff_memory_response_beforeDeq
  assign ff_memory_response_beforeDeq_D_IN = 1'd1 ;
  assign ff_memory_response_beforeDeq_EN =
	     ff_memory_response_dequeueing_whas ;

  // submodule ff_memory_response_beforeEnq
  assign ff_memory_response_beforeEnq_D_IN = 1'd1 ;
  assign ff_memory_response_beforeEnq_EN = EN_inst_response_put ;

  // submodule ff_memory_response_ff
  assign ff_memory_response_ff_D_IN = inst_response_put ;
  assign ff_memory_response_ff_ENQ = CAN_FIRE_RL_ff_memory_response_enqueue ;
  assign ff_memory_response_ff_DEQ = CAN_FIRE_RL_ff_memory_response_dequeue ;
  assign ff_memory_response_ff_CLR = 1'b0 ;

  // remaining internal signals
  module_fn_decompress instance_fn_decompress_0(.fn_decompress_inst(final_instruction__h3646[15:0]),
						.fn_decompress(final_instruction___1__h4662));
  assign IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d155 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       rg_prev[11:0] :
	       (csr_misa_c_c ? rx_from_stage0_first_x[11:0] : rg_prev[11:0]) ;
  assign IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d243 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       rx_from_stage0_first_x[9] :
	       (csr_misa_c_c ?
		  !rx_from_stage0_first_x[8] && rx_from_stage0_first_x[9] :
		  rx_from_stage0_first_x[9]) ;
  assign IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d289 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       !rx_from_stage0_first_x[9] :
	       (csr_misa_c_c ?
		  rx_from_stage0_first_x[8] || !rx_from_stage0_first_x[9] :
		  !rx_from_stage0_first_x[9]) ;
  assign IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d120 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] !=
	       2'b11 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	       2'b11 ||
	       !rx_from_stage0_first_x[8] &&
	       !IF_rx_fromstage0_w_data_whas__0_THEN_rx_fromst_ETC___d100 ;
  assign IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d156 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       ((IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] ==
		 2'b11) ?
		  rx_from_stage0_first_x[11:0] :
		  rg_prev[11:0]) :
	       IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d155 ;
  assign IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d218 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] !=
	       2'b11 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] !=
	       2'b11 &&
	       csr_misa_c_c ;
  assign IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d246 =
	     { (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
		 rx_from_stage0_first_x[8] && rx_from_stage0_first_x[9] :
		 IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d243,
	       rx_from_stage0_first_x[8:0] } ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d103 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[15:14] == 2'b11 &&
	       IF_rg_prev_9_BIT_8_4_THEN_rg_prev_9_BITS_11_TO_ETC___d97 :
	       rx_from_stage0_first_x[12] && csr_misa_c_c ||
	       rx_from_stage0_first_x[8] ||
	       IF_rx_fromstage0_w_data_whas__0_THEN_rx_fromst_ETC___d100 ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d157 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       ((rg_prev[15:14] == 2'b11) ?
		  rx_from_stage0_first_x[11:0] :
		  rg_prev[11:0]) :
	       IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d156 ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d219 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[15:14] != 2'b11 :
	       IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d218 ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d227 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[15:14] == 2'b11 &&
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d225 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d225 ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d248 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       { rg_prev[15:14] != 2'b11,
		 x__h2690,
		 rg_prev[8] && rg_prev[9],
		 rg_prev[8:0] } :
	       { IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d218,
		 x1_avValue_fst_prediction__h4729,
		 IF_IF_rx_fromstage0_w_data_whas__0_THEN_rx_fro_ETC___d246 } ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d260 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[15:14] != 2'b11 ||
	       IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d182 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d182 ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d264 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[15:14] == 2'b11 &&
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d186 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d186 ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d277 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[15:14] == 2'b11 :
	       ((rx_from_stage0_first_x[12] && csr_misa_c_c) ?
		  IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] ==
		  2'b11 :
		  IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
		  2'b11 ||
		  !csr_misa_c_c) ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d291 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       !rg_prev[8] || !rg_prev[9] :
	       ((rx_from_stage0_first_x[12] && csr_misa_c_c) ?
		  !rx_from_stage0_first_x[8] || !rx_from_stage0_first_x[9] :
		  IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d289) ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d299 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[8] && rg_prev[9] :
	       ((rx_from_stage0_first_x[12] && csr_misa_c_c) ?
		  rx_from_stage0_first_x[8] && rx_from_stage0_first_x[9] :
		  IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d243) ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d302 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       !rg_prev[8] :
	       !rx_from_stage0_first_x[8] ;
  assign IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d305 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[8] :
	       rx_from_stage0_first_x[8] ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d182 =
	     ff_memory_response_ff_EMPTY_N ?
	       !ff_memory_response_ff_D_OUT[8] :
	       EN_inst_response_put && !inst_response_put[8] ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d186 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[8] :
	       !EN_inst_response_put || inst_response_put[8] ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d225 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[8] :
	       inst_response_put[8] ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[40:9] :
	       inst_response_put[40:9] ;
  assign IF_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_m_ETC___d176 =
	     rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 ?
	       x1_avValue_snd_fst_address__h4159 :
	       rx_from_stage0_first_x[76:13] ;
  assign IF_rg_prev_9_BIT_8_4_THEN_rg_prev_9_BITS_11_TO_ETC___d97 =
	     x__h2690 <= 2'd1 ;
  assign IF_rx_fromstage0_w_data_whas__0_THEN_rx_fromst_ETC___d100 =
	     rx_from_stage0_first_x[11:10] <= 2'd1 ;
  assign NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d113 =
	     !rg_action &&
	     rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64 &&
	     (!IF_rg_prev_9_BIT_8_4_THEN_rg_prev_9_BITS_11_TO_ETC___d97 ||
	      rg_prev[15:14] != 2'b11) ||
	     (rg_action ||
	      !rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) &&
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11 ||
	      csr_misa_c_c) ;
  assign NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 =
	     !rg_action &&
	     rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64 ||
	     !rx_from_stage0_first_x[12] ||
	     !csr_misa_c_c ||
	     IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] !=
	     2'b11 ;
  assign NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d91 =
	     !rg_action &&
	     rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64 ||
	     rx_from_stage0_first_x[12] && csr_misa_c_c &&
	     IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] ==
	     2'b11 ||
	     !rx_from_stage0_first_x[12] &&
	     IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] !=
	     2'b11 &&
	     csr_misa_c_c ||
	     !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 ;
  assign NOT_rg_receiving_upper_01_67_OR_IF_ff_memory_r_ETC___d270 =
	     !rg_receiving_upper ||
	     (ff_memory_response_ff_EMPTY_N ?
		!ff_memory_response_ff_D_OUT[8] :
		!inst_response_put[8]) ;
  assign cause__h4016 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[7:2] :
	       inst_response_put[7:2] ;
  assign curr_epoch__h1681 = { rg_eEpoch, rg_wEpoch } ;
  assign ff_memory_response_beforeDeq_read_AND_ff_memor_ETC___d19 =
	     ff_memory_response_beforeDeq_Q_OUT &&
	     (ff_memory_response_ff_EMPTY_N || EN_inst_response_put) &&
	     rx_from_stage0_first_deq_rdy_b &&
	     EN_csr_misa_c &&
	     tx_to_stage2_inst_enq_rdy_b &&
	     tx_to_stage2_enq_rdy_b ;
  assign final_instruction__h3646 = tx_to_stage2_inst_enq_data ;
  assign pipedata_instruction__h4651 =
	     (rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	      IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d219) ?
	       final_instruction___1__h4662 :
	       final_instruction__h3646 ;
  assign rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_CONCAT_IF_rg__ETC___d159 =
	     { curr_epoch__h1681,
	       rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 ?
		 IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d157 :
		 rg_prev[11:0] } ;
  assign rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 =
	     curr_epoch__h1681 == y__h2086 ;
  assign rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64 =
	     rg_prev[13:12] == curr_epoch__h1681 ;
  assign rx_from_stage0_first_x_BITS_76_TO_13__q1 =
	     rx_from_stage0_first_x[76:13] ;
  assign x1_avValue_fst_address__h4147 =
	     { rg_prev[93:32], 1'd1, rg_prev[30] } ;
  assign x1_avValue_fst_address__h4153 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] ==
	      2'b11) ?
	       rx_from_stage0_first_x[76:13] :
	       y_avValue_fst_address__h4150 ;
  assign x1_avValue_fst_history__h4736 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       rg_prev[7:0] :
	       rx_from_stage0_first_x[7:0] ;
  assign x1_avValue_fst_prediction__h4721 =
	     csr_misa_c_c ?
	       y_avValue_fst_prediction__h4717 :
	       rx_from_stage0_first_x[11:10] ;
  assign x1_avValue_fst_prediction__h4725 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       rx_from_stage0_first_x[11:10] :
	       x1_avValue_fst_prediction__h4721 ;
  assign x1_avValue_fst_prediction__h4729 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       y_avValue_fst_prediction__h4704 :
	       x1_avValue_fst_prediction__h4725 ;
  assign x1_avValue_fst_prediction__h4733 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       x__h2690 :
	       x1_avValue_fst_prediction__h4729 ;
  assign x1_avValue_snd_fst_address__h4156 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       x1_avValue_fst_address__h4153 :
	       rx_from_stage0_first_x[76:13] ;
  assign x1_avValue_snd_fst_address__h4159 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       x1_avValue_fst_address__h4147 :
	       x1_avValue_snd_fst_address__h4156 ;
  assign x1_avValue_snd_snd_snd_instruction__h3866 =
	     csr_misa_c_c ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[31:16] :
	       rg_prev[29:14] ;
  assign x1_avValue_snd_snd_snd_instruction__h3870 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       rg_prev[29:14] :
	       x1_avValue_snd_snd_snd_instruction__h3866 ;
  assign x1_avValue_snd_snd_snd_pc__h3865 =
	     csr_misa_c_c ? rx_from_stage0_first_x[76:13] : rg_prev[93:30] ;
  assign x1_avValue_snd_snd_snd_pc__h3869 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       rg_prev[93:30] :
	       x1_avValue_snd_snd_snd_pc__h3865 ;
  assign x1_avValue_snd_snd_snd_snd_instruction__h3765 =
	     (rg_prev[15:14] == 2'b11) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[31:16] :
	       rg_prev[29:14] ;
  assign x1_avValue_snd_snd_snd_snd_pc__h3764 =
	     (rg_prev[15:14] == 2'b11) ?
	       rx_from_stage0_first_x[76:13] :
	       rg_prev[93:30] ;
  assign x1_avValue_snd_snd_snd_snd_snd_instruction__h3832 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] ==
	      2'b11) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[31:16] :
	       rg_prev[29:14] ;
  assign x1_avValue_snd_snd_snd_snd_snd_pc__h3831 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[17:16] ==
	      2'b11) ?
	       rx_from_stage0_first_x[76:13] :
	       rg_prev[93:30] ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3874 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       x1_avValue_snd_snd_snd_snd_snd_instruction__h3832 :
	       x1_avValue_snd_snd_snd_instruction__h3870 ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3878 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       x1_avValue_snd_snd_snd_snd_instruction__h3765 :
	       x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3874 ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3873 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       x1_avValue_snd_snd_snd_snd_snd_pc__h3831 :
	       x1_avValue_snd_snd_snd_pc__h3869 ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3877 =
	     (!rg_action &&
	      rg_prev_9_BITS_13_TO_12_0_EQ_rg_eEpoch_1_CONCA_ETC___d64) ?
	       x1_avValue_snd_snd_snd_snd_pc__h3764 :
	       x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3873 ;
  assign x__h2690 = rg_prev[8] ? rg_prev[11:10] : 2'd1 ;
  assign x_instruction__h3680 =
	     rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 ?
	       x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3878 :
	       rg_prev[29:14] ;
  assign x_pc__h3679 =
	     rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 ?
	       x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3877 :
	       rg_prev[93:30] ;
  assign y__h2086 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[1:0] :
	       inst_response_put[1:0] ;
  assign y_avValue_fst_address__h4150 =
	     { rx_from_stage0_first_x_BITS_76_TO_13__q1[63:2],
	       1'd1,
	       rx_from_stage0_first_x_BITS_76_TO_13__q1[0] } ;
  assign y_avValue_fst_prediction__h4704 =
	     rx_from_stage0_first_x[8] ?
	       rx_from_stage0_first_x[11:10] :
	       2'd1 ;
  assign y_avValue_fst_prediction__h4717 =
	     rx_from_stage0_first_x[8] ?
	       2'd1 :
	       rx_from_stage0_first_x[11:10] ;
  assign y_avValue_snd_fst__h3841 =
	     { 16'd0,
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[15:0] } ;
  assign y_avValue_snd_snd_snd_fst__h3718 =
	     { (rg_prev[15:14] == 2'b11) ?
		 IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[15:0] :
		 16'd0,
	       rg_prev[29:14] } ;
  assign y_avValue_snd_snd_snd_fst__h3720 =
	     (rx_from_stage0_first_x[12] && csr_misa_c_c) ?
	       y_avValue_snd_snd_snd_fst__h3779 :
	       y_avValue_snd_snd_snd_fst__h3781 ;
  assign y_avValue_snd_snd_snd_fst__h3779 =
	     { 16'd0,
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[31:16] } ;
  assign y_avValue_snd_snd_snd_fst__h3781 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73[1:0] ==
	      2'b11) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73 :
	       y_avValue_snd_fst__h3841 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_action <= `BSV_ASSIGNMENT_DELAY 1'd1;
	rg_eEpoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_prev <= `BSV_ASSIGNMENT_DELAY
	    94'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
	rg_receiving_upper <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_wEpoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (rg_action_EN) rg_action <= `BSV_ASSIGNMENT_DELAY rg_action_D_IN;
	if (rg_eEpoch_EN) rg_eEpoch <= `BSV_ASSIGNMENT_DELAY rg_eEpoch_D_IN;
	if (rg_prev_EN) rg_prev <= `BSV_ASSIGNMENT_DELAY rg_prev_D_IN;
	if (rg_receiving_upper_EN)
	  rg_receiving_upper <= `BSV_ASSIGNMENT_DELAY rg_receiving_upper_D_IN;
	if (rg_wEpoch_EN) rg_wEpoch <= `BSV_ASSIGNMENT_DELAY rg_wEpoch_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_action = 1'h0;
    rg_eEpoch = 1'h0;
    rg_prev = 94'h2AAAAAAAAAAAAAAAAAAAAAAA;
    rg_receiving_upper = 1'h0;
    rg_wEpoch = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  TASK_testplusargs___d310 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  TASK_testplusargs___d311 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  TASK_testplusargs___d312 = $test$plusargs("l3");
	  #0;
	end
    TASK_testplusargs_10_OR_TASK_testplusargs_11_A_ETC___d318 =
	(TASK_testplusargs___d310 ||
	 TASK_testplusargs___d311 && TASK_testplusargs___d312) &&
	inst_response_put[8];
    TASK_testplusargs_10_OR_TASK_testplusargs_11_A_ETC___d320 =
	(TASK_testplusargs___d310 ||
	 TASK_testplusargs___d311 && TASK_testplusargs___d312) &&
	!inst_response_put[8];
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  v__h5109 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("[%10d", v__h5109, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("[%2d]STAGE1: ", hartid);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("IMem_core_response { ", "word: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("'h%h", inst_response_put[40:9]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  TASK_testplusargs_10_OR_TASK_testplusargs_11_A_ETC___d318)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  TASK_testplusargs_10_OR_TASK_testplusargs_11_A_ETC___d320)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("'h%h", inst_response_put[7:2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("'h%h", inst_response_put[1:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d310 ||
	   TASK_testplusargs___d311 && TASK_testplusargs___d312))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d24 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d25 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d26 = $test$plusargs("l1");
	  #0;
	end
    TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d37 =
	(TASK_testplusargs___d24 ||
	 TASK_testplusargs___d25 && TASK_testplusargs___d26) &&
	!rx_from_stage0_first_x[12];
    TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d40 =
	(TASK_testplusargs___d24 ||
	 TASK_testplusargs___d25 && TASK_testplusargs___d26) &&
	rx_from_stage0_first_x[12];
    TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d46 =
	(TASK_testplusargs___d24 ||
	 TASK_testplusargs___d25 && TASK_testplusargs___d26) &&
	!rx_from_stage0_first_x[9];
    TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d48 =
	(TASK_testplusargs___d24 ||
	 TASK_testplusargs___d25 && TASK_testplusargs___d26) &&
	rx_from_stage0_first_x[9];
    TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d54 =
	(TASK_testplusargs___d24 ||
	 TASK_testplusargs___d25 && TASK_testplusargs___d26) &&
	rx_from_stage0_first_x[8];
    TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d52 =
	(TASK_testplusargs___d24 ||
	 TASK_testplusargs___d25 && TASK_testplusargs___d26) &&
	!rx_from_stage0_first_x[8];
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  v__h1778 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("[%10d", v__h1778, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("[%2d]STAGE1 : Prediction: ", hartid);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("Stage0PC { ", "address: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("'h%h", rx_from_stage0_first_x[76:13]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write(", ", "discard: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d37)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d40)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write(", ", "btbresponse: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("BTBResponse { ", "prediction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("'h%h", rx_from_stage0_first_x[11:10]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write(", ", "btbhit: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d46)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d48)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write(", ", "hi: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d52)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_4_OR_TASK_testplusargs_5_AND_ETC___d54)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write(", ", "history: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("'h%h", rx_from_stage0_first_x[7:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d24 ||
	   TASK_testplusargs___d25 && TASK_testplusargs___d26))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89)
	begin
	  TASK_testplusargs___d125 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89)
	begin
	  TASK_testplusargs___d126 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89)
	begin
	  TASK_testplusargs___d127 = $test$plusargs("l1");
	  #0;
	end
    NOT_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff__ETC___d130 =
	!rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	(TASK_testplusargs___d125 ||
	 TASK_testplusargs___d126 && TASK_testplusargs___d127);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89)
	begin
	  v__h2403 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  NOT_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff__ETC___d130)
	$write("[%10d", v__h2403, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  NOT_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff__ETC___d130)
	$write("[%2d]STAGE1 : Dropping Instruction. ExpEpoch:%b CurrEpoch:%b",
	       hartid,
	       y__h2086,
	       curr_epoch__h1681);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  NOT_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff__ETC___d130)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d161 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d162 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d163 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_61_OR_TASK_testplusargs_62_A_ETC___d183 =
	(TASK_testplusargs___d161 ||
	 TASK_testplusargs___d162 && TASK_testplusargs___d163) &&
	IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d182;
    TASK_testplusargs_61_OR_TASK_testplusargs_62_A_ETC___d187 =
	(TASK_testplusargs___d161 ||
	 TASK_testplusargs___d162 && TASK_testplusargs___d163) &&
	IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d186;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  v__h4084 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("[%10d", v__h4084, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("[%2d]STAGE1 : PC:%h: ",
	       hartid,
	       IF_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_m_ETC___d176);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("IMem_core_response { ", "word: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("'h%h",
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d73);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_61_OR_TASK_testplusargs_62_A_ETC___d183)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_61_OR_TASK_testplusargs_62_A_ETC___d187)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("'h%h", cause__h4016);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("'h%h", y__h2086, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d161 ||
	   TASK_testplusargs___d162 && TASK_testplusargs___d163))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d192 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d193 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d194 = $test$plusargs("l1");
	  #0;
	end
    TASK_testplusargs_92_OR_TASK_testplusargs_93_A_ETC___d198 =
	(TASK_testplusargs___d192 ||
	 TASK_testplusargs___d193 && TASK_testplusargs___d194) &&
	rg_action;
    TASK_testplusargs_92_OR_TASK_testplusargs_93_A_ETC___d199 =
	(TASK_testplusargs___d192 ||
	 TASK_testplusargs___d193 && TASK_testplusargs___d194) &&
	!rg_action;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  v__h4378 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d192 ||
	   TASK_testplusargs___d193 && TASK_testplusargs___d194))
	$write("[%10d", v__h4378, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d192 ||
	   TASK_testplusargs___d193 && TASK_testplusargs___d194))
	$write("[%2d]STAGE1 : rg_action: ", hartid);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_92_OR_TASK_testplusargs_93_A_ETC___d198)
	$write("None");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_92_OR_TASK_testplusargs_93_A_ETC___d199)
	$write("CheckPrev");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d192 ||
	   TASK_testplusargs___d193 && TASK_testplusargs___d194))
	$write(" misa[c]:%b discard:%b rg_receiving_upper:%b",
	       hartid,
	       csr_misa_c_c,
	       rx_from_stage0_first_x[12],
	       rg_receiving_upper);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d192 ||
	   TASK_testplusargs___d193 && TASK_testplusargs___d194))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205)
	begin
	  TASK_testplusargs___d252 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205)
	begin
	  TASK_testplusargs___d253 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205)
	begin
	  TASK_testplusargs___d254 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d261 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d260;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d265 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d264;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d271 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	NOT_rg_receiving_upper_01_67_OR_IF_ff_memory_r_ETC___d270;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d273 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	rg_receiving_upper &&
	IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d225;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d278 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d277;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d280 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d219;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d292 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d291;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d300 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d299;
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d303 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d302;
    rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257 =
	rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254);
    TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d306 =
	(TASK_testplusargs___d252 ||
	 TASK_testplusargs___d253 && TASK_testplusargs___d254) &&
	IF_NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO__ETC___d305;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205)
	begin
	  v__h4867 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("[%10d", v__h4867, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("[%2d]STAGE1 : Enquing: ", hartid);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("PIPE1 { ", "program_counter: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("'h%h",
	       IF_rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_m_ETC___d176);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "instruction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("'h%h", pipedata_instruction__h4651);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("'h%h", curr_epoch__h1681);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d261)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d265)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("'h%h", cause__h4016);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "upper_err: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d271)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d273)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "compressed: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d278)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d280)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "btbresponse: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("BTBResponse { ", "prediction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("'h%h", x1_avValue_fst_prediction__h4733);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "btbhit: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d292)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d300)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "hi: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d303)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d89 &&
	  NOT_rg_action_7_8_AND_rg_prev_9_BITS_13_TO_12__ETC___d205 &&
	  TASK_testplusargs_52_OR_TASK_testplusargs_53_A_ETC___d306)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(", ", "history: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("'h%h", x1_avValue_fst_history__h4736, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_1_CONCAT_rg_wEpoch_2_3_EQ_IF_ff_memo_ETC___d257)
	$write("\n");
  end
  // synopsys translate_on
endmodule  // mkstage1

