//
// Generated by Bluespec Compiler, version 2022.01-5-ge3edf4b1 (build e3edf4b1)
//
// On Fri Apr 15 12:46:50 EDT 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_ma_core_req                O     1 const
// mv_core_resp                   O    65 reg
// RDY_mv_core_resp               O     1 const
// mv_counter_interrupt           O     8
// RDY_mv_counter_interrupt       O     1 const
// RDY_ma_events                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// ma_core_req_req                I    80
// ma_mcountinhibit_mcountinhibit_val  I     8
// ma_mhpminterrupten_v           I     8
// ma_events_e                    I    30
// EN_ma_core_req                 I     1
// EN_ma_events                   I     1
//
// Combinational paths from inputs to outputs:
//   (ma_mcountinhibit_mcountinhibit_val,
//    ma_mhpminterrupten_v) -> mv_counter_interrupt
//
//
// module : implementing read and write methods for group - 5 csrs and related side band            access
//
// Comments on the inlined module `wr_events':
//   wire : whenever an event described in the Events_grp4 occurs, the corresponding bit in             this wire is set for the corresponding counter assigned to be incremented
//
// Comments on the inlined module `wr_mcountinhibit':
//   wire : to hold the current derived value of mcountinhibit
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mk_csr_grp7(CLK,
		   RST_N,

		   ma_core_req_req,
		   EN_ma_core_req,
		   RDY_ma_core_req,

		   mv_core_resp,
		   RDY_mv_core_resp,

		   ma_mcountinhibit_mcountinhibit_val,

		   ma_mhpminterrupten_v,

		   mv_counter_interrupt,
		   RDY_mv_counter_interrupt,

		   ma_events_e,
		   EN_ma_events,
		   RDY_ma_events);
  input  CLK;
  input  RST_N;

  // action method ma_core_req
  input  [79 : 0] ma_core_req_req;
  input  EN_ma_core_req;
  output RDY_ma_core_req;

  // value method mv_core_resp
  output [64 : 0] mv_core_resp;
  output RDY_mv_core_resp;

  // action method ma_mcountinhibit
  input  [7 : 0] ma_mcountinhibit_mcountinhibit_val;

  // action method ma_mhpminterrupten
  input  [7 : 0] ma_mhpminterrupten_v;

  // value method mv_counter_interrupt
  output [7 : 0] mv_counter_interrupt;
  output RDY_mv_counter_interrupt;

  // action method ma_events
  input  [29 : 0] ma_events_e;
  input  EN_ma_events;
  output RDY_ma_events;

  // signals for module outputs
  wire [64 : 0] mv_core_resp;
  wire [7 : 0] mv_counter_interrupt;
  wire RDY_ma_core_req,
       RDY_ma_events,
       RDY_mv_core_resp,
       RDY_mv_counter_interrupt;

  // inlined wires
  reg [64 : 0] rg_resp_to_core_1_wget;
  wire [129 : 0] csr_op_arg_wget;

  // register mhpmcounter_0
  reg [63 : 0] mhpmcounter_0;
  wire [63 : 0] mhpmcounter_0_D_IN;
  wire mhpmcounter_0_EN;

  // register mhpmcounter_1
  reg [63 : 0] mhpmcounter_1;
  wire [63 : 0] mhpmcounter_1_D_IN;
  wire mhpmcounter_1_EN;

  // register mhpmcounter_2
  reg [63 : 0] mhpmcounter_2;
  wire [63 : 0] mhpmcounter_2_D_IN;
  wire mhpmcounter_2_EN;

  // register mhpmcounter_3
  reg [63 : 0] mhpmcounter_3;
  wire [63 : 0] mhpmcounter_3_D_IN;
  wire mhpmcounter_3_EN;

  // register mhpmcounter_4
  reg [63 : 0] mhpmcounter_4;
  wire [63 : 0] mhpmcounter_4_D_IN;
  wire mhpmcounter_4_EN;

  // register mhpmcounter_5
  reg [63 : 0] mhpmcounter_5;
  wire [63 : 0] mhpmcounter_5_D_IN;
  wire mhpmcounter_5_EN;

  // register mhpmcounter_6
  reg [63 : 0] mhpmcounter_6;
  wire [63 : 0] mhpmcounter_6_D_IN;
  wire mhpmcounter_6_EN;

  // register mhpmcounter_7
  reg [63 : 0] mhpmcounter_7;
  wire [63 : 0] mhpmcounter_7_D_IN;
  wire mhpmcounter_7_EN;

  // register mhpmevent_0
  reg [63 : 0] mhpmevent_0;
  wire [63 : 0] mhpmevent_0_D_IN;
  wire mhpmevent_0_EN;

  // register mhpmevent_1
  reg [63 : 0] mhpmevent_1;
  wire [63 : 0] mhpmevent_1_D_IN;
  wire mhpmevent_1_EN;

  // register mhpmevent_2
  reg [63 : 0] mhpmevent_2;
  wire [63 : 0] mhpmevent_2_D_IN;
  wire mhpmevent_2_EN;

  // register mhpmevent_3
  reg [63 : 0] mhpmevent_3;
  wire [63 : 0] mhpmevent_3_D_IN;
  wire mhpmevent_3_EN;

  // register mhpmevent_4
  reg [63 : 0] mhpmevent_4;
  wire [63 : 0] mhpmevent_4_D_IN;
  wire mhpmevent_4_EN;

  // register mhpmevent_5
  reg [63 : 0] mhpmevent_5;
  wire [63 : 0] mhpmevent_5_D_IN;
  wire mhpmevent_5_EN;

  // register mhpmevent_6
  reg [63 : 0] mhpmevent_6;
  wire [63 : 0] mhpmevent_6_D_IN;
  wire mhpmevent_6_EN;

  // register mhpmevent_7
  reg [63 : 0] mhpmevent_7;
  wire [63 : 0] mhpmevent_7_D_IN;
  wire mhpmevent_7_EN;

  // register rg_resp_to_core
  // reg : register to hold the response of this group for a csr operation request
  reg [64 : 0] rg_resp_to_core;
  wire [64 : 0] rg_resp_to_core_D_IN;
  wire rg_resp_to_core_EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_increment_perfmonitors,
       CAN_FIRE_RL_rg_resp_to_core__dreg_update,
       CAN_FIRE_ma_core_req,
       CAN_FIRE_ma_events,
       CAN_FIRE_ma_mcountinhibit,
       CAN_FIRE_ma_mhpminterrupten,
       WILL_FIRE_RL_increment_perfmonitors,
       WILL_FIRE_RL_rg_resp_to_core__dreg_update,
       WILL_FIRE_ma_core_req,
       WILL_FIRE_ma_events,
       WILL_FIRE_ma_mcountinhibit,
       WILL_FIRE_ma_mhpminterrupten;

  // inputs to muxes for submodule ports
  reg [63 : 0] MUX_mhpmcounter_0_write_1__VAL_1;
  wire [63 : 0] MUX_mhpmcounter_0_write_1__VAL_2,
		MUX_mhpmcounter_1_write_1__VAL_2,
		MUX_mhpmcounter_2_write_1__VAL_2,
		MUX_mhpmcounter_3_write_1__VAL_2,
		MUX_mhpmcounter_4_write_1__VAL_2,
		MUX_mhpmcounter_5_write_1__VAL_2,
		MUX_mhpmcounter_6_write_1__VAL_2,
		MUX_mhpmcounter_7_write_1__VAL_2;
  wire MUX_mhpmcounter_0_write_1__SEL_1,
       MUX_mhpmcounter_1_write_1__SEL_1,
       MUX_mhpmcounter_2_write_1__SEL_1,
       MUX_mhpmcounter_3_write_1__SEL_1,
       MUX_mhpmcounter_4_write_1__SEL_1,
       MUX_mhpmcounter_5_write_1__SEL_1,
       MUX_mhpmcounter_6_write_1__SEL_1,
       MUX_mhpmcounter_7_write_1__SEL_1;

  // remaining internal signals
  reg [63 : 0] IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233;
  wire [63 : 0] x__h9648, x_wget_fst__h5449, x_wget_snd_fst__h5534;
  wire [30 : 0] bs__h3481;
  wire [7 : 0] IF_NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0__ETC__q1;
  wire [1 : 0] x_wget_snd_snd__h5535;
  wire NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0_2_E_ETC___d23,
       mhpmevent_1_3_EQ_0_4_OR_NOT_mhpmcounter_1_5_EQ_ETC___d43,
       mhpmevent_2_8_EQ_0_9_OR_NOT_mhpmcounter_2_0_EQ_ETC___d58,
       mhpmevent_3_3_EQ_0_4_OR_NOT_mhpmcounter_3_5_EQ_ETC___d73,
       mhpmevent_4_8_EQ_0_9_OR_NOT_mhpmcounter_4_0_EQ_ETC___d88,
       mhpmevent_5_3_EQ_0_4_OR_NOT_mhpmcounter_5_5_EQ_ETC___d103,
       mhpmevent_6_08_EQ_0_09_OR_NOT_mhpmcounter_6_10_ETC___d118,
       mhpmevent_7_23_EQ_0_24_OR_NOT_mhpmcounter_7_25_ETC___d133,
       x__h3478,
       x__h3621,
       x__h3757,
       x__h3893,
       x__h4029,
       x__h4165,
       x__h4301,
       x__h4436;

  // action method ma_core_req
  assign RDY_ma_core_req = 1'd1 ;
  assign CAN_FIRE_ma_core_req = 1'd1 ;
  assign WILL_FIRE_ma_core_req = EN_ma_core_req ;

  // value method mv_core_resp
  assign mv_core_resp = rg_resp_to_core ;
  assign RDY_mv_core_resp = 1'd1 ;

  // action method ma_mcountinhibit
  assign CAN_FIRE_ma_mcountinhibit = 1'd1 ;
  assign WILL_FIRE_ma_mcountinhibit = 1'd1 ;

  // action method ma_mhpminterrupten
  assign CAN_FIRE_ma_mhpminterrupten = 1'd1 ;
  assign WILL_FIRE_ma_mhpminterrupten = 1'd1 ;

  // value method mv_counter_interrupt
  assign mv_counter_interrupt =
	     { mhpmevent_7 != 64'd0 && mhpmcounter_7 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[7] &&
	       ma_mhpminterrupten_v[7],
	       mhpmevent_6 != 64'd0 && mhpmcounter_6 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[6] &&
	       ma_mhpminterrupten_v[6],
	       mhpmevent_5 != 64'd0 && mhpmcounter_5 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[5] &&
	       ma_mhpminterrupten_v[5],
	       mhpmevent_4 != 64'd0 && mhpmcounter_4 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[4] &&
	       ma_mhpminterrupten_v[4],
	       mhpmevent_3 != 64'd0 && mhpmcounter_3 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[3] &&
	       ma_mhpminterrupten_v[3],
	       mhpmevent_2 != 64'd0 && mhpmcounter_2 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[2] &&
	       ma_mhpminterrupten_v[2],
	       mhpmevent_1 != 64'd0 && mhpmcounter_1 == 64'd0 &&
	       !ma_mcountinhibit_mcountinhibit_val[1] &&
	       ma_mhpminterrupten_v[1],
	       IF_NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0__ETC__q1[0] } ;
  assign RDY_mv_counter_interrupt = 1'b1 ;

  // action method ma_events
  assign RDY_ma_events = 1'd1 ;
  assign CAN_FIRE_ma_events = 1'd1 ;
  assign WILL_FIRE_ma_events = EN_ma_events ;

  // rule RL_increment_perfmonitors
  //   rule : the rule increments the performance monitoring counters
  assign CAN_FIRE_RL_increment_perfmonitors = EN_ma_events ;
  assign WILL_FIRE_RL_increment_perfmonitors =
	     EN_ma_events && !EN_ma_core_req ;

  // rule RL_rg_resp_to_core__dreg_update
  assign CAN_FIRE_RL_rg_resp_to_core__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_rg_resp_to_core__dreg_update = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_mhpmcounter_0_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB18 ;
  assign MUX_mhpmcounter_1_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB19 ;
  assign MUX_mhpmcounter_2_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1A ;
  assign MUX_mhpmcounter_3_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1B ;
  assign MUX_mhpmcounter_4_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1C ;
  assign MUX_mhpmcounter_5_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1D ;
  assign MUX_mhpmcounter_6_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1E ;
  assign MUX_mhpmcounter_7_write_1__SEL_1 =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1F ;
  always@(ma_core_req_req or x__h9648)
  begin
    case (ma_core_req_req[79:68])
      12'h338,
      12'h339,
      12'h33A,
      12'h33B,
      12'h33C,
      12'h33D,
      12'hB18,
      12'hB19,
      12'hB1A,
      12'hB1B,
      12'hB1C,
      12'hB1D,
      12'hB1E,
      12'hB1F:
	  MUX_mhpmcounter_0_write_1__VAL_1 = x__h9648;
      default: MUX_mhpmcounter_0_write_1__VAL_1 = x__h9648;
    endcase
  end
  assign MUX_mhpmcounter_0_write_1__VAL_2 =
	     mhpmcounter_0 + { 63'd0, x__h3478 } ;
  assign MUX_mhpmcounter_1_write_1__VAL_2 =
	     mhpmcounter_1 + { 63'd0, x__h3621 } ;
  assign MUX_mhpmcounter_2_write_1__VAL_2 =
	     mhpmcounter_2 + { 63'd0, x__h3757 } ;
  assign MUX_mhpmcounter_3_write_1__VAL_2 =
	     mhpmcounter_3 + { 63'd0, x__h3893 } ;
  assign MUX_mhpmcounter_4_write_1__VAL_2 =
	     mhpmcounter_4 + { 63'd0, x__h4029 } ;
  assign MUX_mhpmcounter_5_write_1__VAL_2 =
	     mhpmcounter_5 + { 63'd0, x__h4165 } ;
  assign MUX_mhpmcounter_6_write_1__VAL_2 =
	     mhpmcounter_6 + { 63'd0, x__h4301 } ;
  assign MUX_mhpmcounter_7_write_1__VAL_2 =
	     mhpmcounter_7 + { 63'd0, x__h4436 } ;

  // inlined wires
  always@(ma_core_req_req or
	  mhpmevent_0 or
	  mhpmevent_1 or
	  mhpmevent_2 or
	  mhpmevent_3 or
	  mhpmevent_4 or
	  mhpmevent_5 or
	  mhpmevent_6 or
	  mhpmevent_7 or
	  mhpmcounter_0 or
	  mhpmcounter_1 or
	  mhpmcounter_2 or
	  mhpmcounter_3 or
	  mhpmcounter_4 or mhpmcounter_5 or mhpmcounter_6 or mhpmcounter_7)
  begin
    case (ma_core_req_req[79:68])
      12'h338: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_0 };
      12'h339: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_1 };
      12'h33A: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_2 };
      12'h33B: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_3 };
      12'h33C: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_4 };
      12'h33D: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_5 };
      12'h33E: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_6 };
      12'h33F: rg_resp_to_core_1_wget = { 1'd1, mhpmevent_7 };
      12'hB18, 12'hC18: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_0 };
      12'hB19, 12'hC19: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_1 };
      12'hB1A, 12'hC1A: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_2 };
      12'hB1B, 12'hC1B: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_3 };
      12'hB1C, 12'hC1C: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_4 };
      12'hB1D, 12'hC1D: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_5 };
      12'hB1E, 12'hC1E: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_6 };
      12'hB1F, 12'hC1F: rg_resp_to_core_1_wget = { 1'd1, mhpmcounter_7 };
      default: rg_resp_to_core_1_wget = 65'h10000000000000000;
    endcase
  end
  assign csr_op_arg_wget =
	     { ma_core_req_req[67:4],
	       IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233,
	       ma_core_req_req[3:2] } ;

  // register mhpmcounter_0
  assign mhpmcounter_0_D_IN =
	     MUX_mhpmcounter_0_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_0_write_1__VAL_2 ;
  assign mhpmcounter_0_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB18 ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     !IF_NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0__ETC__q1[0] ;

  // register mhpmcounter_1
  assign mhpmcounter_1_D_IN =
	     MUX_mhpmcounter_1_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_1_write_1__VAL_2 ;
  assign mhpmcounter_1_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB19 ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_1_3_EQ_0_4_OR_NOT_mhpmcounter_1_5_EQ_ETC___d43 ;

  // register mhpmcounter_2
  assign mhpmcounter_2_D_IN =
	     MUX_mhpmcounter_2_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_2_write_1__VAL_2 ;
  assign mhpmcounter_2_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1A ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_2_8_EQ_0_9_OR_NOT_mhpmcounter_2_0_EQ_ETC___d58 ;

  // register mhpmcounter_3
  assign mhpmcounter_3_D_IN =
	     MUX_mhpmcounter_3_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_3_write_1__VAL_2 ;
  assign mhpmcounter_3_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1B ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_3_3_EQ_0_4_OR_NOT_mhpmcounter_3_5_EQ_ETC___d73 ;

  // register mhpmcounter_4
  assign mhpmcounter_4_D_IN =
	     MUX_mhpmcounter_4_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_4_write_1__VAL_2 ;
  assign mhpmcounter_4_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1C ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_4_8_EQ_0_9_OR_NOT_mhpmcounter_4_0_EQ_ETC___d88 ;

  // register mhpmcounter_5
  assign mhpmcounter_5_D_IN =
	     MUX_mhpmcounter_5_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_5_write_1__VAL_2 ;
  assign mhpmcounter_5_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1D ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_5_3_EQ_0_4_OR_NOT_mhpmcounter_5_5_EQ_ETC___d103 ;

  // register mhpmcounter_6
  assign mhpmcounter_6_D_IN =
	     MUX_mhpmcounter_6_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_6_write_1__VAL_2 ;
  assign mhpmcounter_6_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1E ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_6_08_EQ_0_09_OR_NOT_mhpmcounter_6_10_ETC___d118 ;

  // register mhpmcounter_7
  assign mhpmcounter_7_D_IN =
	     MUX_mhpmcounter_7_write_1__SEL_1 ?
	       MUX_mhpmcounter_0_write_1__VAL_1 :
	       MUX_mhpmcounter_7_write_1__VAL_2 ;
  assign mhpmcounter_7_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'hB1F ||
	     WILL_FIRE_RL_increment_perfmonitors &&
	     mhpmevent_7_23_EQ_0_24_OR_NOT_mhpmcounter_7_25_ETC___d133 ;

  // register mhpmevent_0
  assign mhpmevent_0_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_0_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h338 ;

  // register mhpmevent_1
  assign mhpmevent_1_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_1_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h339 ;

  // register mhpmevent_2
  assign mhpmevent_2_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_2_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h33A ;

  // register mhpmevent_3
  assign mhpmevent_3_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_3_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h33B ;

  // register mhpmevent_4
  assign mhpmevent_4_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_4_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h33C ;

  // register mhpmevent_5
  assign mhpmevent_5_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_5_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h33D ;

  // register mhpmevent_6
  assign mhpmevent_6_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_6_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h33E ;

  // register mhpmevent_7
  assign mhpmevent_7_D_IN = MUX_mhpmcounter_0_write_1__VAL_1 ;
  assign mhpmevent_7_EN =
	     EN_ma_core_req && ma_core_req_req[79:68] == 12'h33F ;

  // register rg_resp_to_core
  assign rg_resp_to_core_D_IN =
	     EN_ma_core_req ? rg_resp_to_core_1_wget : 65'd0 ;
  assign rg_resp_to_core_EN = 1'd1 ;

  // remaining internal signals
  module_fn_csr_op instance_fn_csr_op_0(.fn_csr_op_writedata(x_wget_fst__h5449),
					.fn_csr_op_readdata(x_wget_snd_fst__h5534),
					.fn_csr_op_op(x_wget_snd_snd__h5535),
					.fn_csr_op(x__h9648));
  assign IF_NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0__ETC__q1 =
	     NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0_2_E_ETC___d23 ?
	       8'd1 :
	       8'd0 ;
  assign NOT_mhpmevent_0_EQ_0_0_1_AND_mhpmcounter_0_2_E_ETC___d23 =
	     mhpmevent_0 != 64'd0 && mhpmcounter_0 == 64'd0 &&
	     !ma_mcountinhibit_mcountinhibit_val[0] &&
	     ma_mhpminterrupten_v[0] ;
  assign bs__h3481 = { ma_events_e, 1'b0 } ;
  assign mhpmevent_1_3_EQ_0_4_OR_NOT_mhpmcounter_1_5_EQ_ETC___d43 =
	     mhpmevent_1 == 64'd0 || mhpmcounter_1 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[1] ||
	     !ma_mhpminterrupten_v[1] ;
  assign mhpmevent_2_8_EQ_0_9_OR_NOT_mhpmcounter_2_0_EQ_ETC___d58 =
	     mhpmevent_2 == 64'd0 || mhpmcounter_2 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[2] ||
	     !ma_mhpminterrupten_v[2] ;
  assign mhpmevent_3_3_EQ_0_4_OR_NOT_mhpmcounter_3_5_EQ_ETC___d73 =
	     mhpmevent_3 == 64'd0 || mhpmcounter_3 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[3] ||
	     !ma_mhpminterrupten_v[3] ;
  assign mhpmevent_4_8_EQ_0_9_OR_NOT_mhpmcounter_4_0_EQ_ETC___d88 =
	     mhpmevent_4 == 64'd0 || mhpmcounter_4 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[4] ||
	     !ma_mhpminterrupten_v[4] ;
  assign mhpmevent_5_3_EQ_0_4_OR_NOT_mhpmcounter_5_5_EQ_ETC___d103 =
	     mhpmevent_5 == 64'd0 || mhpmcounter_5 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[5] ||
	     !ma_mhpminterrupten_v[5] ;
  assign mhpmevent_6_08_EQ_0_09_OR_NOT_mhpmcounter_6_10_ETC___d118 =
	     mhpmevent_6 == 64'd0 || mhpmcounter_6 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[6] ||
	     !ma_mhpminterrupten_v[6] ;
  assign mhpmevent_7_23_EQ_0_24_OR_NOT_mhpmcounter_7_25_ETC___d133 =
	     mhpmevent_7 == 64'd0 || mhpmcounter_7 != 64'd0 ||
	     ma_mcountinhibit_mcountinhibit_val[7] ||
	     !ma_mhpminterrupten_v[7] ;
  assign x__h3478 = bs__h3481[mhpmevent_0[4:0]] ;
  assign x__h3621 = bs__h3481[mhpmevent_1[4:0]] ;
  assign x__h3757 = bs__h3481[mhpmevent_2[4:0]] ;
  assign x__h3893 = bs__h3481[mhpmevent_3[4:0]] ;
  assign x__h4029 = bs__h3481[mhpmevent_4[4:0]] ;
  assign x__h4165 = bs__h3481[mhpmevent_5[4:0]] ;
  assign x__h4301 = bs__h3481[mhpmevent_6[4:0]] ;
  assign x__h4436 = bs__h3481[mhpmevent_7[4:0]] ;
  assign x_wget_fst__h5449 = csr_op_arg_wget[129:66] ;
  assign x_wget_snd_fst__h5534 = csr_op_arg_wget[65:2] ;
  assign x_wget_snd_snd__h5535 = csr_op_arg_wget[1:0] ;
  always@(ma_core_req_req or
	  mhpmevent_7 or
	  mhpmevent_0 or
	  mhpmevent_1 or
	  mhpmevent_2 or
	  mhpmevent_3 or
	  mhpmevent_4 or
	  mhpmevent_5 or
	  mhpmevent_6 or
	  mhpmcounter_0 or
	  mhpmcounter_1 or
	  mhpmcounter_2 or
	  mhpmcounter_3 or
	  mhpmcounter_4 or mhpmcounter_5 or mhpmcounter_6 or mhpmcounter_7)
  begin
    case (ma_core_req_req[79:68])
      12'h338:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_0;
      12'h339:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_1;
      12'h33A:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_2;
      12'h33B:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_3;
      12'h33C:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_4;
      12'h33D:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_5;
      12'h33E:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmevent_6;
      12'hB18:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_0;
      12'hB19:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_1;
      12'hB1A:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_2;
      12'hB1B:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_3;
      12'hB1C:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_4;
      12'hB1D:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_5;
      12'hB1E:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_6;
      12'hB1F:
	  IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
	      mhpmcounter_7;
      default: IF_ma_core_req_req_BITS_79_TO_68_38_EQ_0xB18_3_ETC___d233 =
		   mhpmevent_7;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        mhpmcounter_0 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_1 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_2 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_3 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_4 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_5 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_6 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmcounter_7 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_0 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_1 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_2 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_3 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_4 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_5 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_6 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mhpmevent_7 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	rg_resp_to_core <= `BSV_ASSIGNMENT_DELAY 65'd0;
      end
    else
      begin
        if (mhpmcounter_0_EN)
	  mhpmcounter_0 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_0_D_IN;
	if (mhpmcounter_1_EN)
	  mhpmcounter_1 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_1_D_IN;
	if (mhpmcounter_2_EN)
	  mhpmcounter_2 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_2_D_IN;
	if (mhpmcounter_3_EN)
	  mhpmcounter_3 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_3_D_IN;
	if (mhpmcounter_4_EN)
	  mhpmcounter_4 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_4_D_IN;
	if (mhpmcounter_5_EN)
	  mhpmcounter_5 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_5_D_IN;
	if (mhpmcounter_6_EN)
	  mhpmcounter_6 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_6_D_IN;
	if (mhpmcounter_7_EN)
	  mhpmcounter_7 <= `BSV_ASSIGNMENT_DELAY mhpmcounter_7_D_IN;
	if (mhpmevent_0_EN)
	  mhpmevent_0 <= `BSV_ASSIGNMENT_DELAY mhpmevent_0_D_IN;
	if (mhpmevent_1_EN)
	  mhpmevent_1 <= `BSV_ASSIGNMENT_DELAY mhpmevent_1_D_IN;
	if (mhpmevent_2_EN)
	  mhpmevent_2 <= `BSV_ASSIGNMENT_DELAY mhpmevent_2_D_IN;
	if (mhpmevent_3_EN)
	  mhpmevent_3 <= `BSV_ASSIGNMENT_DELAY mhpmevent_3_D_IN;
	if (mhpmevent_4_EN)
	  mhpmevent_4 <= `BSV_ASSIGNMENT_DELAY mhpmevent_4_D_IN;
	if (mhpmevent_5_EN)
	  mhpmevent_5 <= `BSV_ASSIGNMENT_DELAY mhpmevent_5_D_IN;
	if (mhpmevent_6_EN)
	  mhpmevent_6 <= `BSV_ASSIGNMENT_DELAY mhpmevent_6_D_IN;
	if (mhpmevent_7_EN)
	  mhpmevent_7 <= `BSV_ASSIGNMENT_DELAY mhpmevent_7_D_IN;
	if (rg_resp_to_core_EN)
	  rg_resp_to_core <= `BSV_ASSIGNMENT_DELAY rg_resp_to_core_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    mhpmcounter_0 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_1 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_2 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_3 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_4 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_5 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_6 = 64'hAAAAAAAAAAAAAAAA;
    mhpmcounter_7 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_0 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_1 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_2 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_3 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_4 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_5 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_6 = 64'hAAAAAAAAAAAAAAAA;
    mhpmevent_7 = 64'hAAAAAAAAAAAAAAAA;
    rg_resp_to_core = 65'h0AAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mk_csr_grp7

