//
// Generated by Bluespec Compiler, version 2022.01-5-ge3edf4b1 (build e3edf4b1)
//
// On Fri Apr 15 12:45:58 EDT 2022
//
//
// Ports:
// Name                         I/O  size props
// chk_interrupt                  O     7
// chk_interrupt_prv              I     2
// chk_interrupt_mstatus          I    64
// chk_interrupt_mip              I    19
// chk_interrupt_mie              I    19
// chk_interrupt_mideleg          I    12
//
// Combinational paths from inputs to outputs:
//   (chk_interrupt_prv,
//    chk_interrupt_mstatus,
//    chk_interrupt_mip,
//    chk_interrupt_mie,
//    chk_interrupt_mideleg) -> chk_interrupt
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_chk_interrupt(chk_interrupt_prv,
			    chk_interrupt_mstatus,
			    chk_interrupt_mip,
			    chk_interrupt_mie,
			    chk_interrupt_mideleg,
			    chk_interrupt);
  // value method chk_interrupt
  input  [1 : 0] chk_interrupt_prv;
  input  [63 : 0] chk_interrupt_mstatus;
  input  [18 : 0] chk_interrupt_mip;
  input  [18 : 0] chk_interrupt_mie;
  input  [11 : 0] chk_interrupt_mideleg;
  output [6 : 0] chk_interrupt;

  // signals for module outputs
  wire [6 : 0] chk_interrupt;

  // remaining internal signals
  wire [18 : 0] pending_interrupts__h38,
		s_interrupts__h37,
		x__h156,
		x__h158,
		x__h87,
		x__h99,
		y__h100,
		y__h102,
		y__h157,
		y__h159;
  wire [5 : 0] x__h26;
  wire x__h107, x__h164;

  // value method chk_interrupt
  assign chk_interrupt = { x__h26, pending_interrupts__h38 != 19'd0 } ;

  // remaining internal signals
  assign pending_interrupts__h38 = x__h87 | s_interrupts__h37 ;
  assign s_interrupts__h37 = x__h156 & y__h157 ;
  assign x__h107 = chk_interrupt_prv != 2'd3 || chk_interrupt_mstatus[3] ;
  assign x__h156 = x__h158 & y__h159 ;
  assign x__h158 = chk_interrupt_mie & chk_interrupt_mip ;
  assign x__h164 =
	     chk_interrupt_prv == 2'd0 ||
	     chk_interrupt_mstatus[1] && chk_interrupt_prv == 2'd1 ;
  assign x__h26 =
	     { 1'b1,
	       pending_interrupts__h38[11] ?
		 5'd11 :
		 (pending_interrupts__h38[3] ?
		    5'd3 :
		    (pending_interrupts__h38[7] ?
		       5'd7 :
		       (pending_interrupts__h38[16] ?
			  5'd16 :
			  (pending_interrupts__h38[9] ?
			     5'd9 :
			     (pending_interrupts__h38[1] ?
				5'd1 :
				(pending_interrupts__h38[5] ?
				   5'd5 :
				   (pending_interrupts__h38[8] ?
				      5'd8 :
				      (pending_interrupts__h38[0] ?
					 5'd0 :
					 (pending_interrupts__h38[4] ?
					    5'd4 :
					    5'd31))))))))) } ;
  assign x__h87 = x__h99 & y__h100 ;
  assign x__h99 = x__h158 & y__h102 ;
  assign y__h100 = { 7'd127, ~chk_interrupt_mideleg } ;
  assign y__h102 = {19{x__h107}} ;
  assign y__h157 = {19{x__h164}} ;
  assign y__h159 = { 7'd0, chk_interrupt_mideleg } ;
endmodule  // module_chk_interrupt

